[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 default_realm = SHBANKPP.COM
 dns_lookup_realm = false
 dns_lookup_kdc = false
 ticket_lifetime = 24h
 renew_lifetime = 7d
 forwardable = true

[realms]
 SHBANKPP.COM = {
  kdc = 10.240.99.84
  admin_server = 10.240.99.84
  kdc = 10.240.99.85
 }

 SHBANKUAT.COM = {
  kdc = 10.240.98.155
  admin_server = 10.240.98.155
 }

 SHBANK.COM = {
  kdc = zjkerberos01
  admin_server = zjkerberos01
 }
 TDH = {
  kdc = zjsjzxptcsuat01:1088
  kdc = zjsjzxptcsuat02:1088
 }

[domain_realm]
 .shbankpp.com = SHBANKPP.COM
 shbankpp.com = SHBANKPP.COM
 .shbankuat.com = SHBANKUAT.COM
 shbankuat.com = SHBANKUAT.COM
 .shbank.com = SHBANK.COM
 shbank.com = SHBANK.COM
 .shbank.cdp.com = SHBANKPP.COM
 shbank.cdp.com = SHBANKPP.COM




